### ISSUE TITLE
Merge proof generation library into this one

### ISSUE THREAD

**Issue by BGluth** [0xPolygonZero/proof-protocol-decoder#5]
I think the coupling is strong enough between the proof protocol and the [block proof generation library](https://github.com/0xPolygonZero/plonky-block-proof-gen) that we probably should move that library as a sub-crate into this repo. It's also a bit of a pain to maintain dependency versions between the two libraries, so it's probably worthwhile doing.

**Comment by Nashtare** [comment]
Done in #8.
